# Generated by Django 6.0.3 on 2026-06-01 12:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_act', models.CharField(choices=[('inscription', 'Inscription'), ('paiement', 'Paiement'), ('note', 'Note'), ('annonce', 'Annonce'), ('compte', 'Compte')], max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'activites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('eleve', 'Élève'), ('prof', 'Professeur')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-nom'],
            },
        ),
        migrations.CreateModel(
            name='Concours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('inscription_prepa', models.IntegerField(default=0)),
                ('montant_prepa', models.IntegerField(default=0)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
            options={
                'db_table': 'concours',
                'ordering': ['-nom'],
            },
        ),
        migrations.CreateModel(
            name='InscriptionTemporaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('eleve', 'Élève'), ('prof', 'Professeur')], max_length=20)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('tel_parent', models.CharField(blank=True, max_length=20, null=True)),
                ('niveau', models.CharField(blank=True, max_length=20, null=True)),
                ('specialite', models.CharField(blank=True, max_length=100, null=True)),
                ('code_sms', models.CharField(max_length=6)),
                ('code_expire_at', models.DateTimeField()),
                ('tentatives', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inscriptions_temporaires',
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'matieres',
                'ordering': ['-nom'],
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.user')),
            ],
            options={
                'db_table': 'administrateurs',
            },
            bases=('api.user',),
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.user')),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('tel_parent', models.CharField(blank=True, max_length=20, null=True)),
                ('niveau', models.CharField(blank=True, choices=[('tle', 'Terminale'), ('post_bac', 'Post-Bacc')], max_length=20, null=True)),
            ],
            options={
                'db_table': 'eleves',
            },
            bases=('api.user',),
        ),
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.user')),
                ('specialite', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'professeurs',
            },
            bases=('api.user',),
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('rejetee', 'Rejetée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='api.concours')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='api.user')),
            ],
            options={
                'db_table': 'inscriptions',
                'unique_together': {('eleve', 'concours')},
            },
        ),
        migrations.CreateModel(
            name='MatiereConcours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coefficient', models.IntegerField(default=1)),
                ('concours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matiere_concours', to='api.concours')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matiere_concours', to='api.matiere')),
            ],
            options={
                'db_table': 'matiere_concours',
                'unique_together': {('matiere', 'concours')},
            },
        ),
        migrations.AddField(
            model_name='concours',
            name='matieres',
            field=models.ManyToManyField(related_name='concours', through='api.MatiereConcours', to='api.matiere'),
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.IntegerField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('paye', 'Payé'), ('echoue', 'Échoué')], default='en_attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='api.inscription')),
            ],
            options={
                'db_table': 'paiements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('concours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.concours')),
            ],
            options={
                'db_table': 'sessions',
            },
        ),
        migrations.CreateModel(
            name='LensResultat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens', to='api.session')),
            ],
            options={
                'db_table': 'lens_resultats',
            },
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('type', models.CharField(choices=[('info', 'Information'), ('alerte', 'Alerte'), ('resultat', 'Résultat'), ('autre', 'Autre')], default='info', max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='annonces/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annonces', to='api.admin')),
            ],
            options={
                'db_table': 'annonces',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valeur', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matiere_concours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='api.matiereconcours')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='api.session')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='api.eleve')),
                ('prof', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='api.prof')),
            ],
            options={
                'db_table': 'notes',
                'unique_together': {('eleve', 'session', 'matiere_concours')},
            },
        ),
    ]
