# Generated by Django 6.0.5 on 2026-05-17 16:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('eleve', 'Élève'), ('prof', 'Professeur')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Concours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('inscription_prepa', models.IntegerField(default=0)),
                ('montant_prepa', models.IntegerField(default=0)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
            options={
                'db_table': 'concours',
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'matieres',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.user')),
            ],
            options={
                'db_table': 'administrateurs',
            },
            bases=('api.user',),
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.user')),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('tel_parent', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'eleves',
            },
            bases=('api.user',),
        ),
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.user')),
                ('specialite', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'professeurs',
            },
            bases=('api.user',),
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('rejetee', 'Rejetée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='api.concours')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='api.eleve')),
            ],
            options={
                'db_table': 'inscriptions',
                'unique_together': {('eleve', 'concours')},
            },
        ),
        migrations.CreateModel(
            name='MatiereConcours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coefficient', models.IntegerField(default=1)),
                ('concours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matiere_concours', to='api.concours')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matiere_concours', to='api.matiere')),
            ],
            options={
                'db_table': 'matiere_concours',
                'unique_together': {('matiere', 'concours')},
            },
        ),
        migrations.AddField(
            model_name='concours',
            name='matieres',
            field=models.ManyToManyField(related_name='concours', through='api.MatiereConcours', to='api.matiere'),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('concours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.concours')),
            ],
            options={
                'db_table': 'sessions',
            },
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('type', models.CharField(choices=[('info', 'Information'), ('alerte', 'Alerte'), ('resultat', 'Résultat'), ('autre', 'Autre')], default='info', max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annonces', to='api.admin')),
            ],
            options={
                'db_table': 'annonces',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.IntegerField(choices=[(0, 'En attente'), (1, 'En cours'), (2, 'Payé'), (3, 'Échoué'), (4, 'Remboursé')], default=0)),
                ('montant', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='api.inscription')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='api.eleve')),
            ],
            options={
                'db_table': 'paiements',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valeur', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matiere_concours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='api.matiereconcours')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='api.session')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='api.eleve')),
                ('prof', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='api.prof')),
            ],
            options={
                'db_table': 'notes',
            },
        ),
    ]
