# Generated by Django 6.0.5 on 2026-05-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_inscriptiontemporaire_remove_paiement_eleve_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptiontemporaire',
            name='niveau',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
