# Generated by Django 6.0.5 on 2026-05-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_inscriptiontemporaire_niveau'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='niveau',
            field=models.CharField(blank=True, choices=[('tle', 'Terminale'), ('post_bac', 'Post-Bacc')], max_length=20, null=True),
        ),
    ]
