# Generated by Django 6.0.3 on 2026-05-27 18:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_annonce_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_act', models.CharField(choices=[('inscription', 'Inscription'), ('paiement', 'Paiement'), ('note', 'Note'), ('annonce', 'Annonce'), ('compte', 'Compte')], max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'activites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='annonce',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='concours',
            options={'ordering': ['-nom']},
        ),
        migrations.AlterModelOptions(
            name='matiere',
            options={'ordering': ['-nom']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-nom']},
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('eleve', 'session', 'matiere_concours')},
        ),
    ]
