# Generated by Django 6.0.3 on 2026-05-29 23:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_activite_alter_annonce_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='inscription',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='api.user'),
        ),
        migrations.CreateModel(
            name='LienResultat',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_resultats', to='api.eleve')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_resultats', to='api.session')),
            ],
            options={
                'db_table': 'liens_resultats',
                'unique_together': {('eleve', 'session')},
            },
        ),
    ]
