# Generated by Django 6.0.5 on 2026-05-30 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_eleve_niveau'),
        ('api', '0005_activite_alter_annonce_options_and_more'),
    ]

    operations = [
    ]
